#PROBLEMA DEL AGENTE VIAJERO  
# OPTIMIZAR LA ENTREGA  
# AHORRA COMBUSTIBLE, TIEMPO, DINERO, ETC.
# SE REALIZA CON VÉRTICES Y ARISTAS  


# RUBRICA
#PROBLEMA 
# OBJETIVO  
# COMO LO VAMOS HACER
# DISEÑO DEL ALGORITMO  
# PSEUDOCODIGO  
#    FASES DEL ALLGORITMO 
# MÉTODO IMPLEMENTADO: PORQUE TIPO DE ALGORITMO  
# OPTIMIZACIÓN Y COMPLEJIDAD DEL ALGORITMO 
# ALCANCES Y LÍMITES  
